const fs = require('fs');
const path = require('path');

// Read CSS variables from web/global.css and generate web/app/lib/generatedPalette.ts
const cssPath = path.resolve(__dirname, '..', 'global.css');
const outPath = path.resolve(__dirname, '..', 'app', 'lib', 'generatedPalette.ts');

function extractVariables(cssText) {
  const vars = {};
  // match --plotly-...: value;
  const re = /--([a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m;
  while ((m = re.exec(cssText))) {
    vars[m[1].trim()] = m[2].trim();
  }
  return vars;
}

function toTsPalette(vars) {
  // map expected keys to the Palette shape
  const keys = [
    ['plotly-blue', 'plotlyBlue'],
    ['plotly-orange', 'plotlyOrange'],
    ['plotly-green', 'plotlyGreen'],
    ['plotly-red', 'plotlyRed'],
    ['plotly-purple', 'plotlyPurple'],
    ['plotly-brown', 'plotlyBrown'],
    ['plotly-yellow', 'plotlyYellow'],
  ];

  const entries = keys.map(([cssKey, tsKey]) => {
    const v = vars[cssKey] || '';
    return `  ${tsKey}: '${v}',`;
  });
  return `/* Autogenerated */\n\nimport type { Palette } from './types';\n\nexport const PALETTE: Palette = {\n${entries.join('\n')}\n};`;
}

function main() {
  if (!fs.existsSync(cssPath)) {
    console.error('global.css not found at', cssPath);
    process.exit(1);
  }
  const css = fs.readFileSync(cssPath, 'utf8');
  const vars = extractVariables(css);
  const ts = toTsPalette(vars);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, ts, 'utf8');
  console.log('Generated', outPath);
}

main();
