/* Autogenerated */

import type { Palette } from './types';

export const PALETTE: Palette = {
  plotlyBlue: '#1f77b4',
  plotlyOrange: '#ff7f0e',
  plotlyGreen: '#2ca02c',
  plotlyRed: '#d62728',
  plotlyPurple: '#9467bd',
  plotlyBrown: '#8c564b',
  plotlyYellow: '#d4b400',
};